# Generated by Django 6.0.5 on 2026-05-21 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('summary_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('emotional_state', models.JSONField(blank=True, null=True)),
                ('safety_flag', models.CharField(blank=True, choices=[('RED', 'RED'), ('ORANGE', 'ORANGE'), ('YELLOW', 'YELLOW'), ('GRAY', 'GRAY')], max_length=10, null=True)),
                ('version', models.IntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='chats.chat')),
            ],
            options={
                'db_table': 'summaries',
            },
        ),
    ]
