# Generated by Django 6.0.5 on 2026-05-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
