# Generated by Django 6.0.5 on 2026-06-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_note_summary_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='note',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='note',
        ),
    ]
