# Generated by Django 6.0.5 on 2026-06-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_message_note_remove_summary_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='persona_id',
            field=models.CharField(default='aman', max_length=50),
        ),
    ]
