# Generated by Django 6.0.5 on 2026-07-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chat_persona_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='persona_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
