# Generated by Django 6.0.5 on 2026-07-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_persona_id',
            field=models.CharField(default='aman', max_length=50),
        ),
    ]
