# Generated by Django 6.0.7 on 2026-07-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_default_persona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(default='sunrise-light', max_length=50),
        ),
    ]
